/* PROGRAM STRUCTURE */
FILE ::= PROGRAM_FILE 
    | INTERFACE_FILE
INTERFACE_FILE ::= FUNCTION_HEADER_LIST
FUNCTION_HEADER_LIST ::= FUNCTION_HEADER_LIST FUNCTION_HEADER
    | /*empty*/
PROGRAM_FILE ::= USE_LIST GLOBAL_DECLARATION_LIST

/* IMPORTS */

USE_LIST ::= USE_LIST use <id> OPT_SEMI
    | /* EMPTY */
GLOBAL_DECLARATION_LIST ::= GLOBAL_DECLARATION_LIST GLOBAL_DECLARATION
    | /* EMPTY */
GLOBAL_DECLARATION ::= TYPED_ID OPT_SEMI
    | SCALAR_TYPED_ID '=' GLOBAL_INIT OPT_SEMI
    | FUNCTION_DECLARATION
SCALAR_TYPED_ID ::= <id> : PRIMITIVE
GLOBAL_INIT ::= <integer>
    | '-' <integer>
    | <bool>
    | <char>

/* DECLARATIONS */

FUNCTION_HEADER ::= <id> '(' PARAM_LIST_OPT ')' RETURN_TYPE
FUNCTION_DECLARATION ::= FUNCTION_HEADER BLOCK
PARAM_LIST_OPT ::= PARAM_LIST
    | /* empty */
PARAM_LIST ::= PARAM_LIST ',' TYPED_ID
    | TYPED_ID
RETURN_TYPE ::= ':' TYPE_LIST
    | /* EMPTY */
TYPE_LIST ::= TYPE_LIST ',' TYPE   
    | TYPE

/* TYPES & IDENTIFIERS */

TYPED_ID_LIST ::= TYPED_ID_LIST ',' TYPED_ID
    | TYPED_ID
TYPED_ID ::= <id> : TYPE
TYPE ::= PRIMITIVE ARRAY_DECLARATION 
ARRAY_DECLARATION ::= SIZED_DIM_LIST UNSIZED_DIM_LIST
             | UNSIZED_DIM_LIST
PRIMITIVE ::= 'bool'
    | 'int'
SIZED_ARRAY_DECL ::= SIZED_DIM_LIST UNSIZED_DIM_LIST
SIZED_DIM_LIST ::= SIZED_DIM_LIST '[' CONDITION ']'
                 | '[' CONDITION ']'
UNSIZED_DIM_LIST ::= UNSIZED_DIM_LIST '[' ']'
                   | /* EMPTY */

/* STATEMENTS & BLOCKS */

BLOCK ::= '{' STATEMENT_LIST LAST_STATEMENT_OPT'}'
STATEMENT_LIST ::= STATEMENT_LIST STATEMENT
    | /* EMPTY */
STATEMENT ::= VAR_DECLARATION OPT_SEMI
    | VAR_DECLARATION '=' CONDITION_LIST OPT_SEMI
    | ASSIGNABLE_LIST '=' CONDITION_LIST OPT_SEMI
    | FUNCTION_CALL OPT_SEMI
    | 'if' CONDITION STATEMENT ELSE_OPT
    | 'while' CONDITION STATEMENT 
    | BLOCK
VAR_DECLARATION ::= TYPED_ID_LIST
ELSE_OPT ::= 'else' STATEMENT
    | /* EMPTY */
LAST_STATEMENT_OPT ::= 'return' CONDITION_LIST OPT_SEMI
    | /* EMPTY */ OPT_SEMI
ASSIGNABLE_LIST ::= ASSIGNABLE_LIST ',' ASSIGNABLE
    | ASSIGNABLE
ASSIGNABLE ::= <id>
    | ASSIGNABLE '[' CONDITION ']'
    | '_'
FUNCTION_CALL ::= <id> '(' ARG_LIST_OPT ')'

/* EXPRESSIONS */

CONDITION_LIST_OPT ::= CONDITION_LIST
    | /* EMPTY */
CONDITION_LIST ::= CONDITION_LIST ',' CONDITION
    | CONDITION 
CONDITION_OPT ::= CONDITION
    | /* EMPTY */

/* BINARY LOGIC */

CONDITION ::= CONDITION '|' CONJUNCTION
    | CONJUNCTION 
CONJUNCTION ::= CONJUNCTION '&' EQUALITY 
    | EQUALITY
EQUALITY ::= EQUALITY EQUALITY_OP RELATION
    | RELATION 
EQUALITY_OP ::= '==' 
    | '!='
RELATION ::= RELATION RELATION_OP EXPR
    | EXPR
RELATION_OP ::= '<' 
    | '>' 
    | '>=' 
    | '<='
EXPR ::= EXPR EXPR_OP TERM
    | TERM
EXPR_OP ::= '+' 
    | '-'
TERM ::= TERM TERM_OP UNARY
    | UNARY
TERM_OP ::= '*'
    | '/'
    | '%'
    | '*>>'
UNARY ::= UNARY_OP UNARY
    | FACTOR
UNARY_OP ::= '-'
    | '!'
FACTOR ::= ATOM
    | FACTOR '[' CONDITION ']'
ATOM ::= <id>
    | <char>
    | <integer>
    | <bool> 
    | <string>
    | ARRAY_LITERAL
    | '(' CONDITION ')'
    | FUNCTION_CALL
ARRAY_LITERAL ::= '{' ARRAY_LITERAL_ELEMENTS_OPT '}'
ARRAY_LITERAL_ELEMENTS_OPT ::= CONDITION_LIST
    | CONDITION_LIST ','
    | \* empty*\
OPT_SEMI ::= ';'
    | /* EMPTY */