/* PROGRAM STRUCTURE */

PROGRAM ::= USE_LIST GLOBAL_DECLARATION_LIST

/* IMPORTS */

USE_LIST ::= USE_LIST use <id> OPT_SEMI
    | /* EMPTY */
GLOBAL_DECLARATION_LIST ::= GLOBAL_DECLARATION_LIST GLOBAL_DECLARATION
    | /* EMPTY */
GLOBAL_DECLARATION ::= TYPED_ID OPT_SEMI
    | SCALAR_TYPED_ID '=' GLOBAL_INIT OPT_SEMI
    | FUNCTION_DECLARATION
SCALAR_TYPED_ID ::= <id> : PRIMITIVE
GLOBAL_INIT ::= <integer>
    | '-' <integer>
    | <bool>
    | <char>

/* DECLARATIONS */

FUNCTION_DECLARATION ::= <id> '(' PARAM_LIST_OPT ')' RETURN_TYPE BLOCK
PARAM_LIST_OP ::= PARAM_LIST
    | /* empty */
PARAM_LIST ::= PARAM_LIST ',' TYPED_ID
    | TYPED_ID
RETURN_TYPE ::= ':' TYPE_LIST
    | /* EMPTY */
TYPE_LIST ::= TYPE_LIST ',' TYPE   
    | TYPE

/* TYPES & IDENTIFIERS */
TYPED_ID_LIST ::= TYPED_ID_LIST ',' TYPED_ID
    | TYPED_ID
TYPED_ID ::= <id> : TYPE
TYPE ::= PRIMITIVE ARRAY_DECLARATION
PRIMITIVE = 'bool'
    | 'int'
ARRAY_DECLARATION ::= '[' EXPR_OPT ']' ARRAY_DECLARATION
    | /* EMPTY */

/* STATEMENTS & BLOCKS */

BLOCK ::= '{' STATEMENT_LIST LAST_STATEMENT_OPT'}'
STATEMENT_LIST ::= STATEMENT_LIST STATEMENT
    | /* EMPTY */
STATEMENT ::= VAR_DECLARATION OPT_SEMI
    | VAR_DECLARATION '=' EXPR_LIST OPT_SEMI
    | ASSIGNABLE_LIST '=' EXPR_LIST OPT_SEMI
    | FUNCTION_CALL OPT_SEMI
    | 'if' EXPR STATEMENT ELSE_OPT
    | 'while' EXPR STATEMENT 
    | BLOCK
VAR_DECLARATION ::= TYPED_ID_LIST
ELSE_OPT ::= 'else' STATEMENT
    | /* EMPTY */
LAST_STATEMENT_OPT ::= 'return' EXPR_LIST OPT_SEMI
    | /* EMPTY */ OPT_SEMI
ASSIGNABLE_LIST ::= ASSIGNABLE_LIST ',' ASSIGNABLE
    | ASSIGNABLE
ASSIGNABLE ::= TARGET
    | '_'
TARGET ::= <id>
    | TARGET '[' EXPR ']'
FUNCTION_CALL ::= <id> '(' ARG_LIST_OPT ')'

/* EXPRESSIONS */

RHS_EXPR ::= EXPR_LIST
EXPR_LIST_OPT ::= EXPR_LIST
    | /* EMPTY */
EXPR_LIST ::= EXPR_LIST ',' EXPR
    | EXPR
EXPR_OPT ::= EXPR
    | /* EMPTY */

/* BINARY LOGIC */

CONDITION ::= CONDITION '|' CONJUNCTION
    | CONJUNCTION 
CONJUCTION ::= CONJUNCTION '&' EQUALITY 
    | EQUALITY
EQUALITY ::= EQ_RELATION EQUALITY_OP RELATION
    | RELATION 
EQUALITY_OP ::= '==' 
    | '!='
RELATION ::= RELATION RELATION_OP EXPR
    | EXPR
RELATION_OP ::= '<' 
    | '>' 
    | '>=' 
    | '<='
EXPR ::= EXPR ADD_OP TERM
    | EXPR
    | TERM
ADD_OP ::= '+' 
    | '-'
TERM ::= TERM MUL_OP UNARY
    | UNARY
MUL_OP ::= '*'
    | '/'
    | '%'
    | '*>>'
UNARY ::= UNARY_OP UNARY
    | FACTOR
UNARY_OP ::= '-'
    | '!'
FACTOR ::= ATOM
    | FACTOR '[' EXPR ']'
ATOM ::= <id>
    | <char>
    | <integer>
    | <bool> 
    | <string>
    | ARRAY_LITERAL
    | '(' EXPR ')'
    | <id> '(' ARG_LIST ')'
ARRAY_LITERAL ::= '{' EXPR_LIST_OPT '}'
OPT_SEMI ::= ';'
    | /* EMPTY */